version: '3'

services:

  # Nginx Server
  #this version below with a dockerfile
  #like
  # FROM nginx:latest
  #nginx:
  # build: ./deployment/nginx
  #container_name: nginx-web-server
  #  restart: on-failure
  #  networks:
  #   - kong-net
  # this version below without a dockerfile
  nginx:
    image: nginx:latest
    container_name: nginx-web-server
    restart: on-failure
    networks:
      - kong-net
  # Apache Server
  apache:
    image: httpd
    container_name: apache-server
    restart: on-failure
    networks:
      - kong-net
  
  # HTTPBin
  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    restart: on-failure
    networks:
      - kong-net

  # Application Service A
  api_customer:
    container_name: api-customer
    build: ../API-Customer
    restart: on-failure
    networks:
      - kong-net
  
  
  # Postgres: The database used by Kong
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - kong-net
    restart: on-failure

  # Kong database migration
  kong-migrations:
    image: kong
    container_name: kong-migration
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    command: kong migrations bootstrap
    restart: on-failure
    networks:
      - kong-net
    depends_on:
      - kong-database

  # Kong: The API Gateway
  kong:
    image: kong
    container_name: kong
    environment:
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    restart: on-failure
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    links:
      - kong-database:kong-database
    networks:
      - kong-net
    depends_on:
      - kong-migrations

  # Konga: Kong GUI
  konga:
    image: pantsel/konga
    container_name: konga
    ports:
      - 1337:1337
    depends_on:
      - kong-database
      - kong
    links:
      - kong:kong
    environment:
      - NODE_ENV=production

networks:
  kong-net:
    external: false

volumes:
  postgres: