name: Docker Pull

on:
  create: 
    tags:
      - new-release
    branches:
      - main

jobs:
  pull-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Run Docker Compose
      run: docker-compose -f ../docker-compose.yml